CREATE TABLE "Users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "f_name" varchar NOT NULL,
  "l_name" varchar NOT NULL,
  "sex" varchar,
  "national_id" varchar,
  "email" varchar NOT NULL,
  "profile_path" varchar,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "registered_at" timestamp DEFAULT (now())
);

CREATE TABLE "DormOwners" (
  "dorm_own_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "bank_token" varchar,
  "registered_at" timestamp DEFAULT (now())
);

CREATE TABLE "Dorms" (
  "dorm_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer NOT NULL,
  "dorm_name" varchar NOT NULL,
  "water_cost_per_unit" NUMERIC,
  "power_cost_per_unit" NUMERIC,
  "description" text,
  "lat" NUMERIC NOT NULL,
  "long" NUMERIC NOT NULL,
  "address" varchar,
  "soi" varchar,
  "moo" varchar,
  "road" varchar,
  "prov" varchar,
  "dist" varchar,
  "subdist" varchar,
  "postal_code" integer,
  "medias" JSONB,
  "tel" varchar,
  "line_id" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp,
  "avg_score" NUMERIC DEFAULT 0,
  "likes" integer DEFAULT 0
);

CREATE TABLE "RoomTypes" (
  "room_type_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dorm_id" integer NOT NULL,
  "room_type_name" varchar,
  "room_type_desc" varchar,
  "max_occupancy" integer NOT NULL,
  "rent_per_month" NUMERIC,
  "rent_per_day" NUMERIC,
  "deposit_amount" NUMERIC NOT NULL
);

CREATE TABLE "Rooms" (
  "room_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "room_name" varchar NOT NULL,
  "room_type_id" integer NOT NULL,
  "cur_occupancy" integer,
  "status" varchar
);

CREATE TABLE "DormBookings" (
  "booking_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booker_id" integer NOT NULL,
  "room_id" integer NOT NULL,
  "deposit_amount" NUMERIC,
  "created_at" timestamp DEFAULT (now()),
  "begin_at" timestamp NOT NULL,
  "end_at" timestamp NOT NULL,
  "promo_id" integer,
  "status" varchar
);

CREATE TABLE "FacilityList" (
  "dorm_id" integer,
  "faci_seq" integer,
  "faci_id" integer NOT NULL,
  PRIMARY KEY ("dorm_id", "faci_seq")
);

CREATE TABLE "Facilities" (
  "faci_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "faci_name" varchar NOT NULL
);

CREATE TABLE "SubscriptionPlans" (
  "plan_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "plan_name" varchar NOT NULL,
  "price" NUMERIC NOT NULL,
  "interval" integer DEFAULT 1
);

CREATE TABLE "SubscriptionHistory" (
  "sub_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dorm_id" integer NOT NULL,
  "plan_id" integer NOT NULL,
  "start_date" timestamp DEFAULT (now()),
  "end_date" timestamp NOT NULL,
  "status" varchar
);

CREATE TABLE "UserLikes" (
  "user_id" integer,
  "dorm_id" integer,
  "created_at" timestamp DEFAULT (now()),
  "status" varchar,
  PRIMARY KEY ("user_id", "dorm_id")
);

CREATE TABLE "Reviews" (
  "review_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "dorm_id" integer NOT NULL,
  "content" varchar,
  "score" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Reply" (
  "reply_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "review_id" integer NOT NULL,
  "parent_rep_id" integer,
  "content" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "DormReports" (
  "report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "dorm_id" integer NOT NULL,
  "content" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "Promotion" (
  "promo_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dorm_id" integer NOT NULL,
  "promo_name" varchar NOT NULL,
  "promo_desc" varchar,
  "sale_amount" NUMERIC,
  "created_at" timestamp DEFAULT (now()),
  "start_date" timestamp NOT NULL,
  "end_date" timestamp NOT NULL,
  "status" varchar
);

CREATE TABLE "Chat" (
  "chat_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "participant_id" integer NOT NULL
);

CREATE TABLE "Message" (
  "mess_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" integer,
  "sender_id" integer NOT NULL,
  "recipant_id" integer NOT NULL,
  "content" varchar NOT NULL,
  "medias" jsonb,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "DormAnnouncements" (
  "anno_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dorm_id" integer NOT NULL,
  "anno_name" varchar NOT NULL,
  "anno_desc" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "DormOwners" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Dorms" ADD FOREIGN KEY ("owner_id") REFERENCES "DormOwners" ("dorm_own_id");

ALTER TABLE "RoomTypes" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "Rooms" ADD FOREIGN KEY ("room_type_id") REFERENCES "RoomTypes" ("room_type_id");

ALTER TABLE "DormBookings" ADD FOREIGN KEY ("booker_id") REFERENCES "Users" ("user_id");

ALTER TABLE "DormBookings" ADD FOREIGN KEY ("room_id") REFERENCES "Rooms" ("room_id");

ALTER TABLE "DormBookings" ADD FOREIGN KEY ("promo_id") REFERENCES "Promotion" ("promo_id");

ALTER TABLE "FacilityList" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "FacilityList" ADD FOREIGN KEY ("faci_id") REFERENCES "Facilities" ("faci_id");

ALTER TABLE "SubscriptionHistory" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "SubscriptionHistory" ADD FOREIGN KEY ("plan_id") REFERENCES "SubscriptionPlans" ("plan_id");

ALTER TABLE "UserLikes" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "UserLikes" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Reviews" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "Reply" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Reply" ADD FOREIGN KEY ("review_id") REFERENCES "Reviews" ("review_id");

ALTER TABLE "Reply" ADD FOREIGN KEY ("parent_rep_id") REFERENCES "Reply" ("reply_id");

ALTER TABLE "DormReports" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "DormReports" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "Promotion" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");

ALTER TABLE "Chat" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Chat" ADD FOREIGN KEY ("participant_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Message" ADD FOREIGN KEY ("chat_id") REFERENCES "Chat" ("chat_id");

ALTER TABLE "Message" ADD FOREIGN KEY ("sender_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Message" ADD FOREIGN KEY ("recipant_id") REFERENCES "Users" ("user_id");

ALTER TABLE "DormAnnouncements" ADD FOREIGN KEY ("dorm_id") REFERENCES "Dorms" ("dorm_id");
